name: warp
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=2
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - pytorch-gpu>=2.1.2
  - cuda-version=12.4
  - torchvision
  - nibabel>=2.3.0
  - simpleitk
  - monai
  - meshio
  - pygalmesh
  - warp-lang
  - matplotlib
  - seaborn
  - vtk=9.3.1
  - pyvista
  - trame
  - trame-vtk
  - trame-vuetify
  - ipykernel
  - ipywidgets
  - ipympl
  - pip
  - pip:
    - TotalSegmentator
    - git+ssh://git@github.com/uncbiag/uniGradICONLung.git
