name: warp
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=2
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.4
  - pytorch::torchvision
  - nibabel
  - simpleitk
  - meshio
  - pygalmesh
  - warp-lang
  - matplotlib
  - seaborn
  - ipython
  - ipykernel
  - ipywidgets
  - ipympl
  - pyvista
  - trame
  - trame-vtk
  - trame-vuetify
  - pip
  - pip:
    - TotalSegmentator
