dataset:
    name: "COPDGene"
    root: "data/COPDGene"
    examples:
        subjects: "data/COPDGene/sample1000_2025-07-22.csv"
        state_pairs:
            - ["EXP", "INSP"]
            - ["INSP", "EXP"]
        variant: "2026-08-08"
        pipeline_tags:
            image_resampling: "iso"
            image_segmentation: "tsvf"
            image_registration: "ugil"
            anatomical_regions: "lung"
            material_properties: "bela"
            mesh_generation: "pyg"
            mesh_interpolation: "int"
            forward_simulation: "sim"

preprocessing:
    image_resampling:
        spacing: [1.0, 1.0, 1.0]
        interpolation: "linear"
        default_value: -1000.0
    image_segmentation:
        tasks:
            - method: "TotalSegmentator"
              kwargs:
                  task: "total"
                  roi_subset: ["lung_upper_lobe_right", "lung_middle_lobe_right", "lung_lower_lobe_right", "lung_upper_lobe_left", "lung_lower_lobe_left"]
            - method: "TotalSegmentator"
              kwargs:
                  task: "lung_vessels"
            - method: "VisionFeature"
              kwargs:
                  model: "vista3d"
                  results_dir: "/restricted/projectnb/batmanlab/haozhe/Lung_Mesh_Segment/data/nnUNetv2/nnUNet_results"
            - method: "HU_threshold"
              kwargs:
                  thresholds:
                      lt-950: {"operator": "<", "value": -950}
                      lt-910: {"operator": "<", "value": -910}
                      lt-850: {"operator": "<", "value": -850}
                      gt-700: {"operator": "<", "value": -700}
                      gt-500: {"operator": ">", "value": -500}
                      gt-200: {"operator": ">", "value": -200}
    image_registration:
        method: "unigradicon"
        kwargs:
            model: "gradiconlung"
            io_sim: "lncc2"
            io_iterations: 50
            sigma: 1
            loss_function_masking: true
            intensity_conservation_loss: true
            weights_root: "/projectnb/batmanlab/mragoza/lung-project/network_weights"
    anatomical_regions:
        roi_order: ["lung_upper_lobe_right", "lung_middle_lobe_right", "lung_lower_lobe_right", "lung_upper_lobe_left", "lung_lower_lobe_left"]
        region_filter:
            min_voxels: 30
            keep_largest: true
    material_properties:
        density:
            default: 1000.
            range: [1., 2000.]
            terms:
                image: {'weight': 1.0}
        youngs_modulus:
            default: 2000.
            range: [1., 20000.]
            terms:
                lung_arteries: {'weight': +3000.} #  5000
                lung_veins:    {'weight': +3000.} #  5000
                lung_airways:  {'weight': +6000.} #  8000
                lt-850:        {'weight': -1000.} #  1000
                lt-910:        {'weight':  -500.} #   500
                lt-950:        {'weight':  -250.} #   250
                ggo:           {'weight': +2000.} #  4000
                consolidation: {'weight': +4000.} #  8000
                nodule:        {'weight': +8000.} # 16000
        poisson_ratio:
            default: 0.42
    mesh_generation:
        use_affine_spacing: true
        mesh_parameters:
            max_facet_distance: 0.75
            max_cell_circumradius: 5.0
            lloyd: true
            odt: true
    mesh_interpolation:
        displacement_key: "u_reg"
        interpolate_args: {}
    forward_simulation:
        physics_adapter:
            default_rho: 250
        pde_solver:
            _class: WarpFEMSolver
            scalar_degree: 1
            vector_degree: 1
        boundary_condition:
            type: "mesh_key"
            value: "u_reg"
        output_key: "u_fwd"

optimization:
    targets: ["E"]
    param_specs:
    E:
        mode: "log10"
        mean: 3.4863
        std: 0.3271
    nu:
        mode: "logit"
        min: 0.0001
        max: 0.4999
    rho:
        mode: "log10"
        mean: 2.4
        std: 0.1
    physics_adapter:
        scalar_degree: 1
        vector_degree: 1
    pde_solver:
        _class: WarpFEMSolver
        material_type: "stvk"
        relative_loss: true
        tv_reg_weight: 0.0001
    optimizer:
        _class: LBFGS
        lr: 1.0
        max_iter: 1
        history_size: 10
        line_search_fn: "strong_wolfe"
        global_steps: 1
        local_steps: 1

training:
    random_seed: 1234
    task:
        inputs: ["image"]
        targets: ["E"]
        losses:
            E: "sim"
    split:
        key: "category"
        test_ratio: 0.2
        val_ratio: 0.1
        seed: 0
    transform:
        normalize: true
        image_mean: 0.0
        image_std: 1.0
        apply_mask: true
        do_augment: true
        rand_rotate: true
        rand_reflect: true
        sigma_trans: 4.0
    loader:
        batch_size: 1
        shuffle: true
        num_workers: 0
    model:
        backbone:
            _class: UNet3Dv2
            out_channels: 16
            conv_channels: 16
            n_conv_units: 2
            n_sub_levels: 2
            kernel_size: 3
            relu_leak: 0.1
            norm_type: "group"
            num_groups: 4
            pooling_type: "max"
            upsample_mode: "trilinear"
        param_specs:
            E:
                mode: "log10"
                mean: 3.4863
                std: 0.3271
            nu:
                mode: "logit"
                min: 0.0001
                max: 0.4999
            rho:
                mode: "log10"
                mean: 2.4
                std: 0.1
    physics_adapter:
        default_nu: 0.4
        default_rho: 250
        scalar_degree: 1
        vector_degree: 1
    pde_solver:
        _class: WarpFEMSolver
        relative_loss: true
        tv_reg_weight: 0.0001
    optimizer:
        _class: AdamW
        lr: 0.001
    trainer:
        num_epochs: 100
