dataset:
    name: "COPDGene"
    root: "/restricted/projectnb/batmanlab/mragoza/data/COPDGene"
    subjects: "/restricted/projectnb/batmanlab/mragoza/data/COPDGene/sample1000_2025-07-22.csv"
    state_pairs:
        - ["EXP", "INSP"]
    variant: "2026-09-15"
    pipeline_tags:
        image_resampling:    "iso"
        image_segmentation:  "v3d"
        image_registration:  "gil"
        anatomical_regions:  "lung"
        material_properties: "bela"
        mesh_generation:     "375"
        field_interpolation: "int"
        forward_simulation:  "LE"

preprocessing:
    image_resampling: {"spacing": [1.0, 1.0, 1.0], "interpolator": "bspline", "default_value": -1000.}
    image_segmentation:
        tasks:
          - method: "TotalSegmentator"
            kwargs:
                task: "total"
                roi_subset: ["lung_upper_lobe_right", "lung_middle_lobe_right", "lung_lower_lobe_right", "lung_upper_lobe_left", "lung_lower_lobe_left"]
          - method: "TotalSegmentator"
            kwargs:
                task: "lung_vessels"
          - method: "VisionFeature"
            kwargs:
                model: "vista3d"
                results_dir: "/restricted/projectnb/batmanlab/haozhe/Lung_Mesh_Segment/data/nnUNetv2/nnUNet_results"
          - method: "HU_threshold"
            kwargs:
                thresholds:
                    lt-950: {"operator": "<", "value": -950}
                    lt-910: {"operator": "<", "value": -910}
                    lt-850: {"operator": "<", "value": -850}
                    gt-500: {"operator": ">", "value": -500}
                    gt-200: {"operator": ">", "value": -200}
    image_registration:
        method: "unigradicon"
        kwargs:
            model: "gradiconlung"
            similarity: "lncc2"
            sigma: 1
            iterations: 50
            loss_function_masking: true
            intensity_conservation: true
            weights_root: "/projectnb/batmanlab/mragoza/lung-project/network_weights"
    anatomical_regions:
        roi_order: ["lung_upper_lobe_right", "lung_middle_lobe_right", "lung_lower_lobe_right", "lung_upper_lobe_left", "lung_lower_lobe_left"]
        filter_kws: {"min_voxels": 30, "keep_largest": true}
    material_properties:
        youngs_modulus:
            base_value: 2000.
            terms:
                lung_arteries: +3000.
                lung_veins:    +3000.
                lung_airways:  +6000.
                ggo:           +2000.
                consolidation: +4000.
                nodule:        +8000.
                lt-850:        -1000.
                lt-910:         -500.
                lt-950:         -250.
            sigma: 3.75
            range: [1., 20000.]
        poisson_ratio:
            base_value: 0.42
        density:
            base_value: 350.
    mesh_generation:
        use_search: True
        pygalmesh_kws:
            max_cell_circumradius: 3.75
            max_facet_distance: 1.0
            lloyd: true
            odt: true
    field_interpolation:
        displacement_key: "u_reg"
    forward_simulation:
        pde_solver:
            type: "warp"
            material_type: "linear"
            g_vector: [0., -9.81, 0.]
        boundary_condition: {"type": "mesh_key", "value": "u_reg"}
        output_key: "u_fwd"

optimization:
    parameters:
        E: {"mode": "log10", "mean": 3.301, "std": 1.0}
    pde_solver:
        type: "warp"
        material_type: "linear"
        g_vector: [0., -9.81, 0.]
        relative_loss: true
        tv_reg_weight: 1.e-4
    boundary_condition: {"type": "mesh_key", "value": "u_fwd"}
    optimization_kws:
        type: "LBFGS"
        num_trials: 10
        init_scale: 0.1
        global_steps: 0
        local_steps: 100
        rtol: 1.e-5
        max_iter: 1
        max_eval: 20
        line_search_fn: "strong_wolfe"

training:
    seed: 1234
    task:
        inputs: ["image"]
        targets: ["E"]
        losses: {"E": "sim"}
    split:
        key: "category"
        test_ratio: 0.2
        val_ratio: 0.1
    transform:
        normalize: true
        image_mean: 0.0
        image_std: 1.0
        apply_mask: true
        do_augment: true
        rand_rotate: true
        rand_reflect: true
        rand_translate: 4.0
    loader: {"batch_size": 1, "shuffle": true, "num_workers": 0}
    model:
        backbone:
            _class: UNet3Dv2
            out_channels: 16
            conv_channels: 16
            n_conv_units: 2
            n_sub_levels: 2
            kernel_size: 3
            relu_leak: 0.1
            norm_type: "group"
            num_groups: 4
            pooling_type: "max"
            upsample_mode: "trilinear"
        heads:
            E: {"mode": "log10", "mean": 3.301, "std": 1.0}
    pde_solver:
        type: "warp"
        material_type: "linear"
        g_vector: [0., -9.81, 0.]
        relative_loss: true
        tv_reg_weight: 1.e-5
    optimizer: {"type": "AdamW", "lr": 1.e-3}
    trainer: {"num_epochs": 100}
